### ISSUE TITLE
[Request] Resume Playing

### ISSUE THREAD

**Issue by jcreynolds** [Hypnos3/node-red-contrib-cast#13] opened 2018-10-24 03:59 UTC
A nice feature would be to resume playing audio/video through the castable device(s) if you inject a tts.

Example:  Listening to spotify on google home and a regularly scheduled tts message comes out. It will stop the spotify stream, play the tts message.  Starting spotify stream again requires manual intervention.

Also if you are playing music/media on a castable and a tts message comes out a different device, it would be nice for the music to quiet down.  Then raise back up to the previous volume after all messages are finished.

**Comment by Hypnos3** [comment] 2018-10-24 17:09
Iagree, that this would be a great feature. The API does not provide such functionality. I must check if the Api provides the state of the current playing audio in a way to start it again after the tts output.

**Comment by AndrewBarfield** [comment] 2018-11-14 23:29
I'd like to second this request. I'm looking for a solution and will post it here.

**Comment by eventhorizonbreaker** [comment] 2018-12-12 16:49
I doubt this can be done. What you could do is to read the casting device state before playing tts. When your message is communicated you could request playing the same media URL as before. I don't see a way to actually resume from where you stopped or silence existing stream.

**Comment by Hypnos3** [comment] 2018-12-12 23:17
This was also my first idea. The problem is if any is playing from an app like Spotify or TuneIn, the player does not give an media URL back.

**Comment by eventhorizonbreaker** [comment] 2018-12-13 14:36
Oh, I see. Anyway many thanks for this node. It works really well.

**Comment by rgerrans** [comment] 2019-03-02 13:42
I did find where this node.js project has figured out player controls [ https://github.com/xat/castnow ](url) maybe some of their code could be integrated in (above my pay grade)

**Comment by Paul-Reed** [comment] 2019-03-02 13:46
https://github.com/xat/castnow is a dead link.

**Comment by rgerrans** [comment] 2019-03-02 15:05
I misfilled out the URL tag.  Now fixed, thanks

**Comment by tampa44** [comment] 2019-06-10 07:05
If it is not possible to start the music that got stopped because of the TTS announcement, I don't suppose google assistant would support lowering the volume of the current playing music whilst the announcement is made and then restoring the volume, that way you are not breaking the connection to say the spotify app just muting it.

**Comment by Hypnos3** [comment] 2019-10-23 19:30
Currently I see no way to solve this. The used API is to limited.

**Closed by Hypnos3** 2019-10-23 19:30 UTC
Labels: 👎 wontfix, 💡 enhancement
