### ISSUE TITLE
Port error

### ISSUE THREAD

**Issue by Paul-Reed** [Hypnos3/node-red-contrib-cast#2] opened 2018-09-13 12:46 UTC
Just tried, but does not work for me.
I just get the error shown below.

![porterror](https://user-images.githubusercontent.com/973580/45488984-fa5ae280-b75a-11e8-9b0b-d4dcf9a6d7db.PNG)

Is the default port (8009), the same port as used by `node-red-contrib-chromecast`, because the chromecast node works fine in my system.

**Comment by Hypnos3** [comment] 2018-09-13 22:15
fixed with version 0.0.4 (still not working, caused by open issues)

**Closed by Hypnos3** 2018-09-13 22:15 UTC
